name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker compose and start
        run: docker compose up -d --build

      - name: Wait for services to be ready
        run: |
          docker compose ps
          sleep 20

      - name: Run service tests
        run: docker compose exec -T gateway npm run test

      - name: Lint codebase
        run: docker compose exec -T gateway npm run lint